//
//  SoundType.swift
//
//  Created by Christopher Ladd on 10/2/21.
//

import Foundation

/// The SoundType enum represents all known labels of the `SNClassifierIdentifier.version1` model as of iOS 15.0.
public enum SoundType: String {
    case accordion
    case acoustic_guitar
    case air_conditioner
    case air_horn
    case aircraft
    case airplane
    case alarm_clock
    case ambulance_siren
    case applause
    case artillery_fire
    case babble
    case baby_crying
    case baby_laughter
    case bagpipes
    case banjo
    case basketball_bounce
    case bass_drum
    case bass_guitar
    case bassoon
    case bathtub_filling_washing
    case battle_cry
    case bee_buzz
    case beep
    case bell
    case belly_laugh
    case bicycle
    case bicycle_bell
    case bird
    case bird_chirp_tweet
    case bird_flapping
    case bird_squawk
    case bird_vocalization
    case biting
    case blender
    case boat_water_vehicle
    case boiling
    case booing
    case boom
    case bowed_string_instrument
    case bowling_impact
    case brass_instrument
    case breathing
    case burp
    case bus
    case camera
    case car_horn
    case car_passing_by
    case cat
    case cat_meow
    case cat_purr
    case cello
    case chainsaw
    case chatter
    case cheering
    case chewing
    case chicken
    case chicken_cluck
    case children_shouting
    case chime
    case choir_singing
    case chopping_food
    case chopping_wood
    case chuckle_chortle
    case church_bell
    case civil_defense_siren
    case clapping
    case clarinet
    case click
    case clock
    case coin_dropping
    case cough
    case cow_moo
    case cowbell
    case coyote_howl
    case cricket_chirp
    case crow_caw
    case crowd
    case crumpling_crinkling
    case crushing
    case crying_sobbing
    case cutlery_silverware
    case cymbal
    case didgeridoo
    case disc_scratching
    case dishes_pots_pans
    case dog
    case dog_bark
    case dog_bow_wow
    case dog_growl
    case dog_howl
    case dog_whimper
    case door
    case door_bell
    case door_slam
    case door_sliding
    case double_bass
    case drawer_open_close
    case drill
    case drum
    case drum_kit
    case duck_quack
    case electric_guitar
    case electric_piano
    case electric_shaver
    case electronic_organ
    case elk_bugle
    case emergency_vehicle
    case engine
    case engine_accelerating_revving
    case engine_idling
    case engine_knocking
    case engine_starting
    case eruption
    case finger_snapping
    case fire
    case fire_crackle
    case fire_engine_siren
    case firecracker
    case fireworks
    case flute
    case fly_buzz
    case foghorn
    case fowl
    case french_horn
    case frog
    case frog_croak
    case frying_food
    case gargling
    case gasp
    case giggling
    case glass_breaking
    case glass_clink
    case glockenspiel
    case gong
    case goose_honk
    case guitar
    case guitar_strum
    case guitar_tapping
    case gunshot_gunfire
    case gurgling
    case hair_dryer
    case hammer
    case hammond_organ
    case harmonica
    case harp
    case harpsichord
    case hedge_trimmer
    case helicopter
    case hi_hat
    case hiccup
    case horse_clip_clop
    case horse_neigh
    case humming
    case insect
    case keyboard_musical
    case keys_jangling
    case knock
    case laughter
    case lawn_mower
    case lion_roar
    case liquid_dripping
    case liquid_filling_container
    case liquid_pouring
    case liquid_sloshing
    case liquid_splashing
    case liquid_spraying
    case liquid_squishing
    case liquid_trickle_dribble
    case mallet_percussion
    case mandolin
    case marimba_xylophone
    case mechanical_fan
    case microwave_oven
    case mosquito_buzz
    case motorboat_speedboat
    case motorcycle
    case music
    case nose_blowing
    case oboe
    case ocean
    case orchestra
    case organ
    case owl_hoot
    case percussion
    case person_running
    case person_shuffling
    case person_walking
    case piano
    case pig_oink
    case pigeon_dove_coo
    case playing_badminton
    case playing_hockey
    case playing_squash
    case playing_table_tennis
    case playing_tennis
    case playing_volleyball
    case plucked_string_instrument
    case police_siren
    case power_tool
    case power_windows
    case printer
    case race_car
    case rail_transport
    case railroad_car
    case rain
    case raindrop
    case rapping
    case ratchet_and_pawl
    case rattle_instrument
    case reverse_beeps
    case ringtone
    case rooster_crow
    case rope_skipping
    case rowboat_canoe_kayak
    case sailing
    case saw
    case saxophone
    case scissors
    case screaming
    case scuba_diving
    case sea_waves
    case sewing_machine
    case sheep_bleat
    case shofar
    case shout
    case sigh
    case silence
    case singing
    case singing_bowl
    case sink_filling_washing
    case siren
    case sitar
    case skateboard
    case skiing
    case slap_smack
    case slurp
    case smoke_detector
    case snake_hiss
    case snake_rattle
    case snare_drum
    case sneeze
    case snicker
    case snoring
    case speech
    case squeak
    case steel_guitar_slide_guitar
    case steelpan
    case stream_burbling
    case subway_metro
    case synthesizer
    case tabla
    case tambourine
    case tap
    case tearing
    case telephone
    case telephone_bell_ringing
    case theremin
    case thump_thud
    case thunder
    case thunderstorm
    case tick
    case tick_tock
    case timpani
    case toilet_flush
    case toothbrush
    case traffic_noise
    case train
    case train_horn
    case train_wheels_squealing
    case train_whistle
    case trombone
    case truck
    case trumpet
    case tuning_fork
    case turkey_gobble
    case typewriter
    case typing
    case typing_computer_keyboard
    case ukulele
    case underwater_bubbling
    case vacuum_cleaner
    case vehicle_skidding
    case vibraphone
    case violin_fiddle
    case water
    case water_pump
    case water_tap_faucet
    case waterfall
    case whale_vocalization
    case whispering
    case whistling
    case whoosh_swoosh_swish
    case wind
    case wind_chime
    case wind_instrument
    case wind_noise_microphone
    case wind_rustling_leaves
    case wood_cracking
    case writing
    case yell
    case yodeling
    case zipper
    case zither
}
